version: '3'
services:
  api:
    command: 'npm run start-dev'
    ports:
      - 8888:80
    volumes:
      - ./:/app
    links:
      - database
      - smtp
  database:
    image: mariadb:10.1
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
  smtp:
    image: sj26/mailcatcher
    ports:
      - 1080:1080
volumes:
  db-data:
